# Generated by Django 4.1.1 on 2022-10-19 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCompte', models.CharField(max_length=20, verbose_name='Nom Compte')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=20, verbose_name='Prenom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('courriel', models.EmailField(max_length=254, verbose_name='courriel')),
                ('motDePasse', models.CharField(max_length=30, verbose_name='Mot de passe')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'Homme'), (2, 'Femme')], null=True, verbose_name='Sexe')),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=50, verbose_name='adresse')),
                ('ville', models.CharField(max_length=20, verbose_name='ville')),
                ('codePostale', models.CharField(max_length=7, verbose_name='code postale')),
                ('province', models.CharField(choices=[('QC', 'Quebec'), ('ON', 'Ontario'), ('BC', 'Colombie-Britanique'), ('AB', 'Alberta'), ('PE', 'Île-du-Prince-Édouard'), ('MB', 'Manitoba'), ('NB', 'Nouveau-Brunswick'), ('NS', 'Nouvelle-Écosse'), ('SK', 'Saskatchewan'), ('NL', 'Terre-Neuve-et-Labrador'), ('NU', 'Nunavut'), ('NT', 'Territoires du Nord-Ouest'), ('YT', 'Yukon')], max_length=2, verbose_name='province')),
                ('idCompte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vente.compteuser', verbose_name='id compte')),
            ],
        ),
    ]
