# Generated by Django 4.1.1 on 2022-10-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0002_commande_produit_lignepanier_lignecommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='idCompte',
        ),
        migrations.AlterField(
            model_name='adresse',
            name='province',
            field=models.CharField(choices=[('QC', 'Quebec'), ('ON', 'Ontario'), ('BC', 'Colombie-Britanique'), ('AB', 'Alberta'), ('PE', 'Île-du-Prince-Édouard'), ('MB', 'Manitoba'), ('NB', 'Nouveau-Brunswick'), ('NS', 'Nouvelle-Écosse'), ('SK', 'Saskatchewan'), ('NL', 'Terre-Neuve-et-Labrador'), ('NU', 'Nunavut'), ('NT', 'Territoires du Nord-Ouest'), ('YT', 'Yukon')], max_length=50, verbose_name='province'),
        ),
    ]
