# Generated by Django 4.1.1 on 2022-10-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0003_remove_adresse_idcompte_alter_adresse_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='idCompte',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion_vente.compteuser', verbose_name='id compte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresse',
            name='province',
            field=models.CharField(choices=[('QC', 'Quebec'), ('ON', 'Ontario'), ('BC', 'Colombie-Britanique'), ('AB', 'Alberta'), ('PE', 'Île-du-Prince-Édouard'), ('MB', 'Manitoba'), ('NB', 'Nouveau-Brunswick'), ('NS', 'Nouvelle-Écosse'), ('SK', 'Saskatchewan'), ('NL', 'Terre-Neuve-et-Labrador'), ('NU', 'Nunavut'), ('NT', 'Territoires du Nord-Ouest'), ('YT', 'Yukon')], max_length=3, verbose_name='province'),
        ),
    ]
