# Generated by Django 4.1.1 on 2022-10-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0004_adresse_idcompte_alter_adresse_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='idCompte',
            field=models.IntegerField(verbose_name='id compte'),
        ),
    ]
