# Generated by Django 4.1.2 on 2022-10-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0005_alter_adresse_idcompte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='Produit',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='lignepanier',
            name='idCompte',
        ),
        migrations.RemoveField(
            model_name='lignepanier',
            name='idProduit',
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='nomCompte',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nom Compte'),
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='LigneCommande',
        ),
        migrations.DeleteModel(
            name='LignePanier',
        ),
    ]
