# Generated by Django 4.1.2 on 2022-10-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0007_commande_lignepanier_lignecommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignepanier',
            name='prixUnitair',
        ),
    ]
