# Generated by Django 4.1.2 on 2022-10-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0009_produit_lienphoto_produit_typeproduit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='dateLimite',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='inventaire',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='numLot',
        ),
    ]
