# Generated by Django 4.1.1 on 2022-10-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0012_alter_inventaire_datelimite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='numLot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='numero de lot'),
        ),
    ]
