# Generated by Django 4.1.1 on 2022-10-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0014_alter_inventaire_datelimite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adresse',
        ),
    ]
