# Generated by Django 4.1.1 on 2022-10-23 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0015_delete_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=50, verbose_name='adresse')),
                ('ville', models.CharField(max_length=20, verbose_name='ville')),
                ('codePostale', models.CharField(max_length=7, verbose_name='code postale')),
                ('province', models.CharField(choices=[('QC', 'Quebec'), ('ON', 'Ontario'), ('BC', 'Colombie-Britanique'), ('AB', 'Alberta'), ('PE', 'Île-du-Prince-Édouard'), ('MB', 'Manitoba'), ('NB', 'Nouveau-Brunswick'), ('NS', 'Nouvelle-Écosse'), ('SK', 'Saskatchewan'), ('NL', 'Terre-Neuve-et-Labrador'), ('NU', 'Nunavut'), ('NT', 'Territoires du Nord-Ouest'), ('YT', 'Yukon')], max_length=3, verbose_name='province')),
                ('Compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vente.compteuser', verbose_name='id compte')),
            ],
        ),
    ]
