# Generated by Django 4.1.1 on 2022-10-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0016_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='Compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_vente.compteuser', verbose_name='ID compte'),
        ),
    ]
