# Generated by Django 4.1.1 on 2022-10-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0017_alter_adresse_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='fraisTransport',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='taxe',
        ),
    ]
