# Generated by Django 4.1.1 on 2022-10-26 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0018_remove_commande_fraistransport_remove_commande_taxe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignecommande',
            old_name='Produit',
            new_name='produit',
        ),
    ]
