# Generated by Django 4.1.1 on 2022-10-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0019_rename_produit_lignecommande_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='motant',
            new_name='montant',
        ),
    ]
