# Generated by Django 4.1.1 on 2022-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_vente', '0020_rename_motant_commande_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='motDePasse',
            field=models.CharField(max_length=64, verbose_name='Mot de passe'),
        ),
    ]
